In [3]:
import pandas as pd
import numpy as np

In [7]:
data = pd.read_csv(r'Cost.csv')
data.head()

,int_add,base,bool_and,bool_not,bool_or,closure,float_cond_eq,float_cond_ge,float_cond_gt,float_cond_le,...,func,let_data,let_lamda,int_mult,int_sub,float_add,float_mult,float_sub,int_div,float_div
0,2.570000e-07,0.0001,0.001,0.002,0.001,0.002,0.001,0.001,0.001,0.001,...,0.001,0.001,0.001,0.00001,0.000002,0.000005,0.00001,0.000003,0.00001,0.00001
1,2.570000e-07,0.0001,0.001,0.002,0.001,0.001,0.001,0.001,0.001,0.001,...,0.001,0.001,0.001,0.00001,0.000003,0.000006,0.00001,0.000003,0.00001,0.00001
2,2.570000e-07,0.0001,0.001,0.002,0.001,0.002,0.001,0.001,0.001,0.001,...,0.001,0.001,0.001,0.00001,0.000003,0.000006,0.00001,0.000004,0.00001,0.00001
3,2.570000e-07,0.0001,0.001,0.002,0.001,0.002,0.001,0.001,0.002,0.001,...,0.001,0.001,0.001,0.00001,0.000003,0.000006,0.00001,0.000003,0.00001,0.00001
4,2.570000e-07,0.0001,0.001,0.002,0.001,0.002,0.001,0.001,0.001,0.001,...,0.001,0.001,0.002,0.00001,0.000002,0.000006,0.00001,0.000003,0.00001,0.00001

In [8]:
data.describe()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   int_add        5000 non-null   float64
 1   base           3316 non-null   float64
 2   bool_and       4997 non-null   float64
 3   bool_not       5000 non-null   float64
 4   bool_or        855 non-null    float64
 5   closure        5000 non-null   float64
 6   float_cond_eq  4840 non-null   float64
 7   float_cond_ge  4755 non-null   float64
 8   float_cond_gt  4808 non-null   float64
 9   float_cond_le  4870 non-null   float64
 10  float_cond_lt  4873 non-null   float64
 11  int_cond_eq    4829 non-null   float64
 12  int_cond_ge    4895 non-null   float64
 13  int_cond_gt    4765 non-null   float64
 14  int_cond_le    4909 non-null   float64
 15  int_cond_lt    4944 non-null   float64
 16  func           3715 non-null   float64
 17  let_data       4931 non-null   float64
 18  let_lamda      4962 non-null   float64
 19  int_mult       4515 non-null   float64
 20  int_sub        5000 non-null   float64
 21  float_add      5000 non-null   float64
 22  float_mult     4402 non-null   float64
 23  float_sub      5000 non-null   float64
 24  int_div        4148 non-null   float64
 25  float_div      4199 non-null   float64
dtypes: float64(26)
memory usage: 208.0 MB

In [9]:
data = data.fillna(data.median())

In [10]:
data.describe()

,int_add,base,bool_and,bool_not,bool_or,closure,float_cond_eq,float_cond_ge,float_cond_gt,float_cond_le,...,func,let_data,let_lamda,int_mult,int_sub,float_add,float_mult,float_sub,int_div,float_div
count,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,...,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,2.570947e-07,1.000385e-04,1.000699e-03,1.999961e-03,1.000045e-03,2.000916e-03,1.000496e-03,1.000211e-03,1.000326e-03,1.000509e-03,...,1.000073e-03,1.001161e-03,1.001304e-03,1.000346e-05,2.001818e-06,5.999170e-06,1.000180e-05,3.002831e-06,1.000015e-05,1.000041e-05
std,9.727286e-09,3.451428e-05,2.807493e-05,3.353182e-05,7.372756e-06,5.604929e-05,2.363490e-05,1.749530e-05,3.232836e-05,2.297993e-05,...,2.288149e-05,9.321751e-05,1.216957e-04,2.220204e-07,4.352599e-08,9.644412e-08,8.120738e-07,1.758617e-07,4.784140e-08,1.755095e-07
min,2.430000e-07,1.000000e-04,1.000000e-03,1.000000e-03,1.000000e-03,1.000000e-03,1.000000e-03,1.000000e-03,1.000000e-03,1.000000e-03,...,1.000000e-03,1.000000e-03,1.000000e-03,1.000000e-05,1.000000e-06,5.000000e-06,1.000000e-05,3.000000e-06,1.000000e-05,1.000000e-05
25%,2.570000e-07,1.000000e-04,1.000000e-03,2.000000e-03,1.000000e-03,2.000000e-03,1.000000e-03,1.000000e-03,1.000000e-03,1.000000e-03,...,1.000000e-03,1.000000e-03,1.000000e-03,1.000000e-05,2.000000e-06,6.000000e-06,1.000000e-05,3.000000e-06,1.000000e-05,1.000000e-05
50%,2.570000e-07,1.000000e-04,1.000000e-03,2.000000e-03,1.000000e-03,2.000000e-03,1.000000e-03,1.000000e-03,1.000000e-03,1.000000e-03,...,1.000000e-03,1.000000e-03,1.000000e-03,1.000000e-05,2.000000e-06,6.000000e-06,1.000000e-05,3.000000e-06,1.000000e-05,1.000000e-05
75%,2.570000e-07,1.000000e-04,1.000000e-03,2.000000e-03,1.000000e-03,2.000000e-03,1.000000e-03,1.000000e-03,1.000000e-03,1.000000e-03,...,1.000000e-03,1.000000e-03,1.000000e-03,1.000000e-05,2.000000e-06,6.000000e-06,1.000000e-05,3.000000e-06,1.000000e-05,1.000000e-05
max,1.780000e-06,3.540000e-02,7.000000e-03,6.000000e-03,3.000000e-03,2.200000e-02,7.000000e-03,9.000000e-03,1.900000e-02,4.000000e-03,...,2.200000e-02,9.000000e-02,1.190000e-01,9.000000e-05,5.000000e-06,6.700000e-05,8.300000e-04,1.030000e-04,4.000000e-05,1.800000e-04